name: Auto update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Dependency update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b dependency-update
    - name: Update dependencies
      run: |
        go get -u ./...
    - name: Git commit
      id: commit
      continue-on-error: true
      run: |
        git add go.mod go.sum
        git commit -m "Go get -u"
    - name: Git push
      if: steps.commit.outcome == 'success'
      run: |
        git push origin dependency-update --force
    - name: Create Pull Request
      if: steps.commit.outcome == 'success'
      uses: actions/github-script@v7
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Dependency update',
            owner,
            repo,
            head: 'dependency-update',
            base: '${{ github.event.repository.default_branch }}',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });